//! Generates the C# project that wraps a plugin's Rust library.
//!
//! Every value here comes from the compiled library (see [`crate::metadata`]), so the
//! generated identity cannot disagree with the plugin it wraps. That matters because
//! BTCPay's packer reads identity from the C# type at packaging time, when no native
//! library is loadable, so the values have to be baked in as constants rather than fetched
//! at runtime.
//!
//! The output is build output: written under `target/`, never edited, regenerated each
//! build. A plugin repository contains no C# at all.

use std::path::Path;

use crate::config::Config;
use crate::metadata::PluginMetadata;

/// Writes the C# project for `metadata` into `out_dir`.
pub fn generate(metadata: &PluginMetadata, config: &Config, out_dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(out_dir)
        .map_err(|e| format!("could not create {}: {e}", out_dir.display()))?;

    write(
        &out_dir.join(format!("{}.csproj", metadata.identifier)),
        &csproj(metadata, config),
    )?;
    write(&out_dir.join("Plugin.cs"), &plugin_cs(metadata))?;
    let controller = out_dir.join("SettingsController.cs");
    if metadata.has_settings_page {
        write(&controller, &settings_controller_cs(metadata))?;
    } else {
        // A previous build may have written one when the plugin still had a page.
        let _ = std::fs::remove_file(&controller);
    }
    Ok(())
}

fn write(path: &Path, contents: &str) -> Result<(), String> {
    std::fs::write(path, contents).map_err(|e| format!("could not write {}: {e}", path.display()))
}

fn csproj(metadata: &PluginMetadata, config: &Config) -> String {
    let id = &metadata.identifier;
    let tag = &config.build.btcpay_tag;
    format!(
        r#"<Project Sdk="Microsoft.NET.Sdk">

  <!--
    GENERATED by `cargo btcpay`. Do not edit: it is rewritten on every build.
    Values come from the compiled plugin library, so they always match the Rust source.
  -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>{id}</AssemblyName>
    <RootNamespace>{id}</RootNamespace>
    <Version>{version}</Version>
    <Description>{description}</Description>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CS8632;CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <!-- Referencing BTCPayServer must not drop its artifacts into the published plugin. -->
  <ItemDefinitionGroup>
    <ProjectReference>
      <Properties>StaticWebAssetsEnabled=false</Properties>
      <Private>false</Private>
      <ExcludeAssets>runtime;native;build;buildTransitive;contentFiles</ExcludeAssets>
    </ProjectReference>
  </ItemDefinitionGroup>

  <!-- BTCPayServer.Abstractions is not on NuGet, so this builds against a source checkout
       of {tag}, which `cargo btcpay` fetches and caches. -->
  <ItemGroup>
    <ProjectReference Include="$(BtcpayServerProject)" />
  </ItemGroup>

  <!-- The host assemblies ship with each plugin (Private=true) so they load into the
       plugin's own AssemblyLoadContext, keeping plugins isolated from one another. -->
  <ItemGroup>
    <ProjectReference Include="$(BtcpayRsHostProject)"><Private>true</Private></ProjectReference>
    <ProjectReference Include="$(BtcpayRsHostBtcpayProject)"><Private>true</Private></ProjectReference>
  </ItemGroup>

  <!-- The native library sits flat beside the plugin assembly: BTCPay's load context
       resolves natives from deps.json, which a loose file never populates. -->
  <ItemGroup>
    <None Include="$(BtcpayRsNativeLibrary)"
          CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
"#,
        id = id,
        tag = tag,
        version = xml_escape(&metadata.version),
        description = xml_escape(&metadata.description),
    )
}

fn plugin_cs(metadata: &PluginMetadata) -> String {
    let dependencies = metadata
        .dependencies
        .iter()
        .map(|d| {
            format!(
                "        new() {{ Identifier = \"{}\", Condition = \"{}\" }},",
                cs_escape(&d.identifier),
                cs_escape(&d.condition)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"// GENERATED by `cargo btcpay`. Do not edit: it is rewritten on every build.
//
// These constants duplicate what the Rust library reports, deliberately: BTCPay's packer
// instantiates this type at packaging time, when the native library cannot be loaded. They
// are generated from that library, and the host re-checks them against it at startup, so
// the two cannot silently disagree.

using BtcpayRs.Host.BTCPay;
using BTCPayServer.Abstractions.Contracts;
using BTCPayServer.Models.ServerViewModels;
using BTCPayServer.Plugins.GlobalSearch;
using Microsoft.Extensions.DependencyInjection;

// MVC discovers views only from the plugin assembly and from assemblies it names here. The
// generic settings views live in BtcpayRs.Host.BTCPay, so without this the settings page
// cannot find its view.
[assembly: Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssembly("BtcpayRs.Host.BTCPay")]

namespace {namespace};

public class Plugin : RustPluginBase
{{
    public override string Identifier => "{identifier}";
    public override string Name => "{name}";
    public override string Description => "{description}";

    public override IBTCPayServerPlugin.PluginDependency[] Dependencies {{ get; }} =
    [
{dependencies}
    ];
{navigation}}}
"#,
        namespace = metadata.identifier,
        identifier = cs_escape(&metadata.identifier),
        name = cs_escape(&metadata.name),
        description = cs_escape(&metadata.description),
        dependencies = dependencies,
        navigation = navigation_cs(metadata),
    )
}

/// Registers the settings page under Server Settings, and in the search box.
///
/// Emitted only when the plugin has a page to link to, so a plugin with nothing to configure
/// adds no menu clutter. Linked by absolute path rather than by controller name: every
/// plugin's generated controller is called `SettingsController`, so routing by name would be
/// ambiguous once two are installed.
fn navigation_cs(metadata: &PluginMetadata) -> String {
    if !metadata.has_settings_page {
        return String::new();
    }

    format!(
        r#"
    /// <summary>Where this plugin's settings page lives. Drives the server menu entry.</summary>
    public override string SettingsPath => "/{route}";

    public override void Execute(IServiceCollection services)
    {{
        services.AddSingleton(new ServicesViewModel.OtherExternalService
        {{
            Name = "{name}",
            Link = "/{route}",
        }});

        services.AddStaticSearch(new ActionResultItemViewModel
        {{
            Title = "{name} settings",
            Keywords = ["{name}", "{identifier}"],
            Controller = "Settings",
            Action = "Index",
            Category = "Server",
            RequiredPolicy = BTCPayServer.Client.Policies.CanModifyServerSettings,
        }});

        base.Execute(services);
    }}
"#,
        name = cs_escape(&metadata.name),
        identifier = cs_escape(&metadata.identifier),
        route = route_for(&metadata.identifier),
    )
}

/// The settings page controller.
///
/// Generated per plugin rather than shipped in the host, because MVC matches on route
/// templates: two plugins carrying a controller with the same template would collide at
/// request time. Giving each plugin a literal route of its own removes the ambiguity.
fn settings_controller_cs(metadata: &PluginMetadata) -> String {
    format!(
        r#"// GENERATED by `cargo btcpay`. Do not edit: it is rewritten on every build.

using BtcpayRs.Host.BTCPay;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace {namespace};

/// <summary>Serves this plugin's settings page.</summary>
[Authorize(Policy = BTCPayServer.Client.Policies.CanModifyServerSettings,
           AuthenticationSchemes = BTCPayServer.Abstractions.Constants.AuthenticationSchemes.Cookie)]
[Route("{route}")]
public class SettingsController : RustPluginSettingsControllerBase
{{
    public SettingsController(RustPluginHostedService plugin) : base(plugin) {{ }}
}}
"#,
        namespace = metadata.identifier,
        route = route_for(&metadata.identifier),
    )
}

/// A URL-safe path segment for a plugin, derived from its identifier.
///
/// Lowercased and dotted segments joined with hyphens, so `Acme.Plugins.Thing` serves its
/// pages from `plugins/acme-plugins-thing/<page>`.
pub fn route_for(identifier: &str) -> String {
    let slug: String = identifier
        .chars()
        .map(|c| match c {
            '.' => '-',
            c if c.is_ascii_alphanumeric() => c.to_ascii_lowercase(),
            _ => '-',
        })
        .collect();
    format!("plugins/{slug}")
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn cs_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::metadata::Dependency;

    fn sample() -> PluginMetadata {
        PluginMetadata {
            identifier: "Acme.Plugins.Thing".into(),
            name: "Thing".into(),
            version: "1.2.3".into(),
            description: "Does things.".into(),
            abi_version: 2,
            has_settings_page: true,
            dependencies: vec![Dependency {
                identifier: "BTCPayServer".into(),
                condition: ">=2.4.0".into(),
            }],
        }
    }

    #[test]
    fn the_generated_class_carries_the_libraded_identity() {
        let cs = plugin_cs(&sample());

        assert!(cs.contains(r#"Identifier => "Acme.Plugins.Thing""#));
        assert!(cs.contains(r#"Name => "Thing""#));
        assert!(cs.contains(r#"Identifier = "BTCPayServer", Condition = ">=2.4.0""#));
        assert!(
            cs.contains("RustPluginBase"),
            "must extend the host base class"
        );
    }

    #[test]
    fn generated_files_are_marked_as_generated() {
        let md = sample();
        let config = Config {
            build: Default::default(),
        };

        assert!(plugin_cs(&md).starts_with("// GENERATED"));
        assert!(csproj(&md, &config).contains("GENERATED"));
    }

    #[test]
    fn xml_special_characters_in_a_description_cannot_break_the_project_file() {
        let mut md = sample();
        md.description = "Bread & butter <tags>".into();

        let xml = csproj(
            &md,
            &Config {
                build: Default::default(),
            },
        );

        assert!(xml.contains("Bread &amp; butter &lt;tags&gt;"));
        assert!(!xml.contains("Bread & butter"));
    }

    #[test]
    fn a_quote_in_metadata_cannot_break_out_of_the_csharp_string() {
        let mut md = sample();
        md.name = r#"say "hi""#.into();

        let cs = plugin_cs(&md);

        assert!(cs.contains(r#"Name => "say \"hi\"""#), "got: {cs}");
    }

    #[test]
    fn both_files_are_written_with_the_expected_names() {
        let dir = tempfile::tempdir().unwrap();
        let md = sample();

        generate(
            &md,
            &Config {
                build: Default::default(),
            },
            dir.path(),
        )
        .unwrap();

        assert!(dir.path().join("Acme.Plugins.Thing.csproj").exists());
        assert!(dir.path().join("Plugin.cs").exists());
    }
}
