[package]
name = "btcpay-plugin"
description = "The contract a BTCPay Server plugin written in Rust implements."
readme = "README.md"
keywords = ["btcpay", "bitcoin", "plugin", "uniffi", "ffi"]
categories = ["development-tools::ffi", "cryptography::cryptocurrencies"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
uniffi.workspace = true
btcpay-ui.workspace = true
thiserror = "2"
ctor = "0.2"
btcpay-plugin-macros.workspace = true
